train:
  device: "mps"
  total_steps: 10000000
  rollout_len: 1024
  update_epochs: 4
  minibatches: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.05

  critic_target_ema: 0.01
  lr_actor: 0.0001
  lr_critic: 0.0002
  critic_weight_decay: 0.0
  qr_kappa: 1.0
  n_quantiles: 51
  mean_anchor_coef: 0.1
  exploration_eps: 0.03

  max_grad_norm: 0.5
  seed: 0
  log_interval: 1000
  eval_every_steps: 100000

  wandb_project: "mappo-gridworld"
  wandb_run_name: "case_study_1_2_distributional_v33"
  wandb_mode: "online"
  log_video: false

  param_type: "distributional"
  risk_enable: true         # turn on risk-aware mixing
  risk_beta: 0.4            # 0.0..1.0 trade-off (performance vs safety)
  cvar_alpha: 0.05          # tail level for CVaR

  # federation
  num_communication_rounds: 90
  local_epochs_per_round: 40
  n_clients: 6
  client_weights: [0.20, 0.19, 0.17, 0.16, 0.15, 0.13]

env:
  H: 10
  W: 10

  starts: [[9, 0], [0, 0], [9, 9]]
  goals: [[0, 5]]

  obstacle_template_id: "warehouse_a"
  obstacles: []

  # 3x2 hazard centered: rows 4..6, cols 4..5 (inclusive)
  hazard_zone_bounds: [3, 4, 5, 5]
  hazard_zone_cells: null

  hazard_prob: 0.40
  hazard_loss: 120.0

  step_cost: -0.1
  goal_reward: 100.0
  catastrophe_reward: -300.0

  invalid_move_penalty: -0.1
  max_steps: 120

  n_agents: 3
  slip_prob: 0.15
  sample_active_hazard_each_episode: false
  block_on_collision: true

  critic_obs_mode: "grid"
  actor_obs_mode: "ego"
  ego_k: 5

  has_objects: true
  object_starts: [[3, 1], [6, 1], [4, 8]]
  object_goal: [9, 5]
  require_two_pushers: false
  object_push_penalty: 0.05
  object_reward: 300.0

  use_push_step_cost: true
  push_step_cost: 0.0
  push_fail_penalty: 0.0

  allow_multi_agent_on_goal: true
  allow_objects_stack_on_object_goal: true

fedrl:
  enable_ae_aux: false         # must be true to run and log AE
  fedrl_d_latent: 128          # optional; default 128
  fedrl_enc_lr: 1.0e-3         # optional
  fedrl_dec_lr: 5.0e-4         # optional
  fedrl_rec_lambda: 1.0e-2     # not used in the loss, only kept for compatibility
  fedrl_latent_hw: 5

  enabled: true
  alpha: 0.5
  beta: 1.0
  radius_abs: 0
  radius_rel: 0.20

  agg_hazard_eps: 1.0e-3   # denominator epsilon in 1/(eps + hazard)
  agg_w_max: 30.0          # cap on any single client's weight; set 0.0 to disable