model:
  device: "mps"
  lr: 1e-4
  batch_size: 1
  grad_clip: 10.0

  seeds:
    - 0
    - 1
    - 2
    - 3

federation:
  num_communication_rounds: 500
  local_epochs_per_round: 2
  n_clients: 5
  n_arms: 3
  cvar_alpha: 0.1
  client_weights: 
    - 0.8
    - 0.05
    - 0.05
    - 0.05
    - 0.05

# fedrl specific
fedrl:
  kappa: 0.05
  server_kd_lr: 1e-1
  ot_reg: 1e-1
  ot_p: 1
  server_kd_steps: 10